version: '3.7'

services:
  back:
    build: ./backend
    volumes:
      - ./backend:/usr/src/omnistack/
      - /usr/src/omnistack/node_modules
    ports:
      - 3333:3333
    command: npm start
  front:
    build: ./frontend
    depends_on:
      - back
    volumes:
      - ./frontend:/usr/src/omnistack/
      - /usr/src/omnistack/node_modules
    ports:
      - 3000:3000
    environment:
      - CI=true
      - HOST=0.0.0.0
      - CI=true
    command: npm start